import { money } from "../components/FeeMoney";

export default function ReceiptPrint({ receipt }) {
  if (!receipt) return null;

  const schoolName =
    receipt?.school?.name ||
    receipt?.schoolName ||
    receipt?.invoice?.schoolName ||
    "School";

  const student =
    receipt?.student || receipt?.invoice?.student || receipt?.payment?.student;

  const inv = receipt?.invoice;
  const pay = receipt?.payment;

  return (
    <div id="print-fees-receipt" className="print-only">
      <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>
        <div>
          <div style={{ fontSize: 18, fontWeight: 700 }}>{schoolName}</div>
          <div style={{ fontSize: 12, opacity: 0.8 }}>Fees Receipt</div>
        </div>

        <div style={{ textAlign: "right", fontSize: 12 }}>
          <div>
            <strong>Receipt No:</strong>{" "}
            {pay?.receiptNo || receipt?.receiptNo || pay?.id || "-"}
          </div>
          <div>
            <strong>Date:</strong>{" "}
            {pay?.createdAt
              ? new Date(pay.createdAt).toLocaleString()
              : new Date().toLocaleString()}
          </div>
        </div>
      </div>

      <hr style={{ margin: "10px 0" }} />

      <div style={{ fontSize: 12, lineHeight: 1.4 }}>
        <div>
          <strong>Student:</strong>{" "}
          {student
            ? `${student.firstName || ""} ${student.lastName || ""}`.trim() ||
              student.name ||
              "-"
            : "-"}
        </div>
        <div>
          <strong>Adm No:</strong> {student?.admissionNo || student?.adm || "-"}
        </div>
        <div>
          <strong>Class:</strong> {student?.class?.name || student?.className || "-"}
        </div>
      </div>

      <hr style={{ margin: "10px 0" }} />

      <table className="print-table" style={{ fontSize: 12 }}>
        <tbody>
          <tr>
            <td><strong>Invoice</strong></td>
            <td>{inv?.invoiceNo || inv?.id || "-"}</td>
          </tr>
          <tr>
            <td><strong>Year / Term</strong></td>
            <td>
              {(inv?.year ?? receipt?.year ?? "-")} / {(inv?.term ?? receipt?.term ?? "-")}
            </td>
          </tr>
          <tr>
            <td><strong>Method</strong></td>
            <td>{pay?.method || receipt?.method || "-"}</td>
          </tr>
          <tr>
            <td><strong>Reference</strong></td>
            <td>{pay?.reference || receipt?.reference || "-"}</td>
          </tr>
          <tr>
            <td><strong>Amount Paid</strong></td>
            <td>{money(pay?.amount ?? receipt?.amount ?? 0)}</td>
          </tr>
          <tr>
            <td><strong>Invoice Total</strong></td>
            <td>{money(inv?.total ?? receipt?.total ?? 0)}</td>
          </tr>
          <tr>
            <td><strong>Balance</strong></td>
            <td>{money(inv?.balance ?? receipt?.balance ?? 0)}</td>
          </tr>
        </tbody>
      </table>

      <div style={{ marginTop: 12, fontSize: 12 }}>
        <div>Served by: {receipt?.servedBy || receipt?.user?.name || "-"}</div>
        <div style={{ marginTop: 6, opacity: 0.8 }}>
          Generated by SMS • {new Date().toLocaleString()}
        </div>
      </div>
    </div>
  );
}
